import "./globals.css";
import Header from "./Header";

export const metadata = {
	title: "Zac's Website",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<title>Zac's Website</title>
			</head>
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
}
